version: '3'

services:
  db:
    container_name: transactions_manager_db
    image: postgres:10.12-alpine
    ports: [ "5432:5432" ]
    volumes: [ ".app_data/postgres/data:/var/lib/postgresql/data" ]
    environment:
      - POSTGRES_DB=transactions_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  .app_data:
